/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as OrderConfirmationIdRouteImport } from './routes/order-confirmation.$id'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerProductsIndexRouteImport } from './routes/seller.products.index'
import { Route as SellerProductsNewRouteImport } from './routes/seller.products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/account/wishlist',
  path: '/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationIdRoute = OrderConfirmationIdRouteImport.update({
  id: '/order-confirmation/$id',
  path: '/order-confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/seller/analytics',
  path: '/seller/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: '/seller/products/',
  path: '/seller/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsNewRoute = SellerProductsNewRouteImport.update({
  id: '/seller/products/new',
  path: '/seller/products/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/account/': typeof AccountIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/products/': typeof SellerProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/account': typeof AccountIndexRoute
  '/products': typeof ProductsIndexRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/products': typeof SellerProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/account/': typeof AccountIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/products/': typeof SellerProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/order-confirmation/$id'
    | '/products/$slug'
    | '/seller/analytics'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/account/'
    | '/products/'
    | '/seller/products/new'
    | '/seller/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/order-confirmation/$id'
    | '/products/$slug'
    | '/seller/analytics'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/account'
    | '/products'
    | '/seller/products/new'
    | '/seller/products'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/search'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/order-confirmation/$id'
    | '/products/$slug'
    | '/seller/analytics'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/account/'
    | '/products/'
    | '/seller/products/new'
    | '/seller/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OrderConfirmationIdRoute: typeof OrderConfirmationIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SellerProductsNewRoute: typeof SellerProductsNewRoute
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$id': {
      id: '/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/order-confirmation/$id'
      preLoaderRoute: typeof OrderConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/seller/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/': {
      id: '/seller/products/'
      path: '/seller/products'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof SellerProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/new': {
      id: '/seller/products/new'
      path: '/seller/products/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof SellerProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  OrderConfirmationIdRoute: OrderConfirmationIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  AccountIndexRoute: AccountIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SellerProductsNewRoute: SellerProductsNewRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
